version: '3'

services:
  fastapi:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - temp_files:/app/temp_files

  streamlit:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - temp_files:/app/temp_files
    environment:
      - API_URL=http://fastapi:8000
    depends_on:
      - fastapi

volumes:
  temp_files:
